### ISSUE TITLE
Error during build

### ISSUE THREAD

**Issue by Peter-St** [fredg02/usb4java-for-eclipse#1]
Hello Fredg02,

I'm getting an error message during the last build command : "mvn clean verify -f usb4java-parent/pom.xml"

MSG:

$ mvn clean verify -f usb4java-parent/pom.xml
[INFO] Scanning for projects...
[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[ERROR] Child module /usb4java-for-eclipse-master/usb4java-parent/../usb4java/pom-tycho.xml of /usb4java-for-eclipse-master/usb4java-parent/pom.xml does not exist @ 
[ERROR] Child module /usb4java-for-eclipse-master/usb4java-parent/../usb4java-javax/pom-tycho.xml of /usb4java-for-eclipse-master/usb4java-parent/pom.xml does not exist @ 
 @ 
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]   
[ERROR]   The project org.usb4java:usb4java-parent:1.0.0 (/usb4java-for-eclipse-master/usb4java-parent/pom.xml) has 2 errors
[ERROR]     Child module /usb4java-for-eclipse-master/usb4java-parent/../usb4java/pom-tycho.xml of /home/peter/Downloads/UVC_Kamera/usb4java-for-eclipse-master/usb4java-parent/pom.xml does not exist
[ERROR]     Child module /usb4java-for-eclipse-master/usb4java-parent/../usb4java-javax/pom-tycho.xml of /usb4java-for-eclipse-master/usb4java-parent/pom.xml does not exist
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException

Any Solutions ?

**Comment by fredg02** [comment]
Sorry, forgot to add `git submodule update --init` to the instructions. I also fixed the submodule URLs.  Please re-clone the repository and follow the instructions.

**Comment by Peter-St** [comment]
Hello Fred,

everything worked for the eclipse plug-in.

Thanks,

Peter
